services:
  webhook:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webhook
    environment:
      - DATABASE_URL=
      - NODE_ENV=
      - HTTP_PORT=
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASSWORD=
      - FROM_EMAIL=
      - T0_EMAIL=
    ports:
      - "3000:3000"